[package]
name = "demo_wasm"
version = "0.1.0"
authors = ["biceneutron <biceneutron@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
renet = { path = "../renet", features = ["transport_webrtc"] }
cfg-if = "1.0.0"
base64 = "0.21.2"
env_logger = "0.10.0"
log = "0.4.17"
serde_json = "1.0"
serde = { version = "1.0.102", features = ["derive"] }

# native server
# str0m = { git = "https://github.com/algesten/str0m.git" } # should be optional (features = transport_webrtc, target_arch != wasm32)
# rouille = { version = "3.5.0", features = ["ssl"] }


# for wasm client
# [target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.84" # should be optional (features = transport_webrtc, target_arch = wasm32)
js-sys = "0.3" # should be optional (features = transport_webrtc, target_arch = wasm32)
wasm-bindgen-futures = "0.4.24" # should be optional (features = transport_webrtc, target_arch = wasm32)

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }


# for wasm client
# [target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
[dependencies.web-sys]
version = "0.3.22"
features = [
  "Event",
  "XmlHttpRequest",
  "ProgressEvent",
  "MessageEvent",
  "RtcPeerConnection",
  "RtcSignalingState",
  "RtcSdpType",
  "RtcSessionDescription",
  "RtcSessionDescriptionInit",
  "RtcPeerConnectionIceEvent",
  "RtcPeerConnectionState",
  "RtcIceCandidate",
  "RtcIceCandidateInit",
  "RtcDataChannel",
  "RtcDataChannelEvent",
  "RtcDataChannelState"
]


# for native server
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
str0m = { git = "https://github.com/algesten/str0m.git" } # should be optional (features = transport_webrtc, target_arch != wasm32)
rouille = { version = "3.5.0", features = ["ssl"] }


[dev-dependencies]
wasm-bindgen-test = "0.3.34"


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
